// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ActualTimes struct {
	ActualBlockOff  string `json:"actualBlockOff"`
	ActualTakeOff   string `json:"actualTakeOff"`
	ActualTouchDown string `json:"actualTouchDown"`
	ActualBlockOn   string `json:"actualBlockOn"`
}

type Coordinates struct {
	Latitude  string `json:"latitude"`
	Longitude string `json:"longitude"`
}

type Delay struct {
	Code    string `json:"code"`
	Code2   string `json:"code2"`
	Minutes string `json:"minutes"`
}

type EstimatedTimes struct {
	EstimatedBlockOff  string `json:"estimatedBlockOff"`
	EstimatedTakeOff   string `json:"estimatedTakeOff"`
	EstimatedTouchDown string `json:"estimatedTouchDown"`
	EstimatedBlockOn   string `json:"estimatedBlockOn"`
}

type Flight struct {
	UniqueID                  string          `json:"uniqueId"`
	TailNumber                string          `json:"tailNumber"`
	FlightNumber              string          `json:"flightNumber"`
	ScheduledDepartureAirport string          `json:"scheduledDepartureAirport"`
	ScheduledArrivalAirport   string          `json:"scheduledArrivalAirport"`
	Std                       string          `json:"std"`
	Sta                       string          `json:"sta"`
	OffsetDa                  string          `json:"offsetDa"`
	OffsetAa                  string          `json:"offsetAa"`
	DepartureGate             string          `json:"departureGate"`
	ActualTimes               *ActualTimes    `json:"actualTimes"`
	EstimatedTimes            *EstimatedTimes `json:"estimatedTimes"`
	Delays                    []*Delay        `json:"delays,omitempty"`
	Fuels                     []*Fuel         `json:"fuels,omitempty"`
}

type FlightAndStations struct {
	Flight   *Flight    `json:"flight"`
	Stations []*Station `json:"stations"`
}

type Fuel struct {
	Type         string `json:"type"`
	Source       string `json:"source"`
	Quantity     string `json:"quantity"`
	QuantityUnit string `json:"quantityUnit"`
	Density      string `json:"density"`
	DensityUnit  string `json:"densityUnit"`
}

type LocationDetails struct {
	CountryCode       string       `json:"countryCode"`
	CityCode          string       `json:"cityCode"`
	ProvinceStateCode string       `json:"provinceStateCode"`
	TimeZoneCode      string       `json:"timeZoneCode"`
	Coordinates       *Coordinates `json:"coordinates"`
}

type Query struct {
}

type Station struct {
	Allowed         bool             `json:"allowed"`
	LocationDetails *LocationDetails `json:"locationDetails"`
	CurrencyCode    string           `json:"currencyCode"`
	InActive        bool             `json:"inActive"`
	FullName        string           `json:"fullName"`
	StationCode     string           `json:"stationCode"`
}
